---
--- Generated by Luanalysis
--- Created by 李灿滔.
--- DateTime: 2022/10/26 下午 07:27
---
local voucherId = ARGV[1]

local userId = ARGV[2]

local orderId = ARGV[3]


local stockKey = 'seckill:stock:' .. voucherId

local orderKey = 'seckill:order:' .. voucherId
---脚本业务
---判断库存是否充足
if (tonumber(redis.call('get',stockKey)) <=0) then
    ---库存小于等于0 库存不足 返回1
    return 1
end

---判断是否已经下过相同订单
if (redis.call('sismember',orderKey,userId) ==1) then
    ---是 不满足一人一单 返回2
    return 2
end

---扣减库存 incrby stockKey -1
redis.call('incrby',stockKey,-1)

---下单  (保存用户) sadd orderKey userId
redis.call('sadd',orderKey,userId)

-----发送消息到消息队列 XADD stream.orders * k1 v1 k2 v2 ...
--redis.call('XADD','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0





